### ISSUE TITLE
[10 beta] PAUSE makes adventure to hang

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#14] opened 2017-03-11 01:23 UTC
If a _condact_ includes a PAUSE 1 or more, browser hangs.
I have tried on Firefox and Chromium

**Comment by cibersheep** [comment] 2017-03-11 15:45
It's related to #11

**Comment by Utodev** [comment] 2017-03-12 13:19
I'm closing this one as I'm unable to reproduce it, and #11 is still open until we can gather more info.

**Closed by Utodev** 2017-03-12 13:19 UTC
